version: "3.9"

services:
  stable-diffusion-api:
    build: .
    container_name: stable-diffusion-api
    ports:
      - "5002:5002"
    environment:
      - LORA_MODEL_PATH=/app/ume_modern_pixelart.safetensors
    volumes:
      - ./generated:/app/generated
      - ./ume_modern_pixelart.safetensors:/app/ume_modern_pixelart.safetensors:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    runtime: nvidia
